//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baballonia.Assets {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baballonia.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Administrator Mode Warning 的本地化字符串。
        /// </summary>
        public static string AdminWarning_Header {
            get {
                return ResourceManager.GetString("AdminWarning_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not run Baballonia as admin! There is no need, and it prevents eye tracking calibrations from working. 的本地化字符串。
        /// </summary>
        public static string AdminWarning_Message {
            get {
                return ResourceManager.GetString("AdminWarning_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to start calibration! 的本地化字符串。
        /// </summary>
        public static string Aero_Calibration_Failed {
            get {
                return ResourceManager.GetString("Aero_Calibration_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eye tracking calibration successful! 的本地化字符串。
        /// </summary>
        public static string Aero_Calibration_Success {
            get {
                return ResourceManager.GetString("Aero_Calibration_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to start camera streaming! 的本地化字符串。
        /// </summary>
        public static string Aero_CameraStream_Failed {
            get {
                return ResourceManager.GetString("Aero_CameraStream_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The gaze overlay program is already running! Please close it and try again. 的本地化字符串。
        /// </summary>
        public static string Aero_Overlay_AlreadyRunning {
            get {
                return ResourceManager.GetString("Aero_Overlay_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to stop/cleanup overlay! 的本地化字符串。
        /// </summary>
        public static string Aero_Overlay_CleanupFailed {
            get {
                return ResourceManager.GetString("Aero_Overlay_CleanupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The gaze overlay program does not exist! 的本地化字符串。
        /// </summary>
        public static string Aero_Overlay_NotFound {
            get {
                return ResourceManager.GetString("Aero_Overlay_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SteamVR is not running. Please run it and try again. 的本地化字符串。
        /// </summary>
        public static string Aero_SteamVR_NotRunning {
            get {
                return ResourceManager.GetString("Aero_SteamVR_NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cheek Expressions 的本地化字符串。
        /// </summary>
        public static string Calibration_Cheek_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Cheek_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eye Expressions 的本地化字符串。
        /// </summary>
        public static string Calibration_Eye_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Eye_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevents eyes from looking out in opposite directions, and improves pupil stability. 的本地化字符串。
        /// </summary>
        public static string Calibration_Eye_Expressions_Stabilize_Eyes_Description {
            get {
                return ResourceManager.GetString("Calibration_Eye_Expressions_Stabilize_Eyes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stabilize Eyes 的本地化字符串。
        /// </summary>
        public static string Calibration_Eye_Expressions_Stabilize_Eyes_Header {
            get {
                return ResourceManager.GetString("Calibration_Eye_Expressions_Stabilize_Eyes_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calibrate Eyelids Openness (3s) 的本地化字符串。
        /// </summary>
        public static string Calibration_Eyelid_Button {
            get {
                return ResourceManager.GetString("Calibration_Eyelid_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eyelid calibration canceled. 的本地化字符串。
        /// </summary>
        public static string Calibration_Eyelid_Status_Canceled {
            get {
                return ResourceManager.GetString("Calibration_Eyelid_Status_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collecting eyelid samples... blink and open naturally. 的本地化字符串。
        /// </summary>
        public static string Calibration_Eyelid_Status_Collecting {
            get {
                return ResourceManager.GetString("Calibration_Eyelid_Status_Collecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eyelid calibration complete. 的本地化字符串。
        /// </summary>
        public static string Calibration_Eyelid_Status_Done {
            get {
                return ResourceManager.GetString("Calibration_Eyelid_Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eyelid calibration failed: {0} 的本地化字符串。
        /// </summary>
        public static string Calibration_Eyelid_Status_Error {
            get {
                return ResourceManager.GetString("Calibration_Eyelid_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eyelid calibration unavailable. Ensure the pfld model is enabled. 的本地化字符串。
        /// </summary>
        public static string Calibration_Eyelid_Status_Unavailable {
            get {
                return ResourceManager.GetString("Calibration_Eyelid_Status_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • Raising the 的本地化字符串。
        /// </summary>
        public static string Calibration_Instructions_Bullet1_1 {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Bullet1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value requires a stronger expression before it starts to show. 的本地化字符串。
        /// </summary>
        public static string Calibration_Instructions_Bullet1_2 {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Bullet1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • Lowering the 的本地化字符串。
        /// </summary>
        public static string Calibration_Instructions_Bullet2_1 {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Bullet2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value means a smaller expression will reach 100% faster. 的本地化字符串。
        /// </summary>
        public static string Calibration_Instructions_Bullet2_2 {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Bullet2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The below sliders are used to calibrate the 的本地化字符串。
        /// </summary>
        public static string Calibration_Instructions_Line1 {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of your face expressions. 的本地化字符串。
        /// </summary>
        public static string Calibration_Instructions_Line1_2 {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Line1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum 的本地化字符串。
        /// </summary>
        public static string Calibration_Instructions_Maximum {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum 的本地化字符串。
        /// </summary>
        public static string Calibration_Instructions_Minimum {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sensitivity 的本地化字符串。
        /// </summary>
        public static string Calibration_Instructions_Sensitivity {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jaw Expressions 的本地化字符串。
        /// </summary>
        public static string Calibration_Jaw_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Jaw_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouth Expressions 的本地化字符串。
        /// </summary>
        public static string Calibration_Mouth_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Mouth_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nose Expressions 的本地化字符串。
        /// </summary>
        public static string Calibration_Nose_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Nose_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Maximums 的本地化字符串。
        /// </summary>
        public static string Calibration_Reset_Maximums {
            get {
                return ResourceManager.GetString("Calibration_Reset_Maximums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Minimums 的本地化字符串。
        /// </summary>
        public static string Calibration_Reset_Minimums {
            get {
                return ResourceManager.GetString("Calibration_Reset_Minimums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calibration 的本地化字符串。
        /// </summary>
        public static string Calibration_Title_Header {
            get {
                return ResourceManager.GetString("Calibration_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tongue Expressions 的本地化字符串。
        /// </summary>
        public static string Calibration_Tongue_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Tongue_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start typing... 的本地化字符串。
        /// </summary>
        public static string Common_Start_Typing {
            get {
                return ResourceManager.GetString("Common_Start_Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dismiss 的本地化字符串。
        /// </summary>
        public static string DropOverlay_Dismiss_Button {
            get {
                return ResourceManager.GetString("DropOverlay_Dismiss_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t show this warning again 的本地化字符串。
        /// </summary>
        public static string DropOverlay_DontShowAgain {
            get {
                return ResourceManager.GetString("DropOverlay_DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Important! 的本地化字符串。
        /// </summary>
        public static string DropOverlay_Important_Header {
            get {
                return ResourceManager.GetString("DropOverlay_Important_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Newer babble trackers have a 20 second delay after being plugged in before they can be used. It will make a USB plugging-in sound when it is ready! 的本地化字符串。
        /// </summary>
        public static string DropOverlay_Message {
            get {
                return ResourceManager.GetString("DropOverlay_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Custom Firmware 的本地化字符串。
        /// </summary>
        public static string Firmware_Custom_Firmware_Load {
            get {
                return ResourceManager.GetString("Firmware_Custom_Firmware_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle wired/wireless mode 的本地化字符串。
        /// </summary>
        public static string Firmware_Device_Configuration_Description {
            get {
                return ResourceManager.GetString("Firmware_Device_Configuration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Configuration 的本地化字符串。
        /// </summary>
        public static string Firmware_Device_Configuration_Header {
            get {
                return ResourceManager.GetString("Firmware_Device_Configuration_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • After powering on/connecting your device you will have 20 seconds to press &quot;Refresh&quot; and select your device from the dropdown 的本地化字符串。
        /// </summary>
        public static string Firmware_Device_Instructions_1 {
            get {
                return ResourceManager.GetString("Firmware_Device_Instructions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • Certain configuration operations will take a little bit! 的本地化字符串。
        /// </summary>
        public static string Firmware_Device_Instructions_2 {
            get {
                return ResourceManager.GetString("Firmware_Device_Instructions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle wired/wireless mode 的本地化字符串。
        /// </summary>
        public static string Firmware_Device_Mode_Header {
            get {
                return ResourceManager.GetString("Firmware_Device_Mode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • You WILL need to restart your tracker after changing the mode 的本地化字符串。
        /// </summary>
        public static string Firmware_Device_Mode_Instruction_1 {
            get {
                return ResourceManager.GetString("Firmware_Device_Mode_Instruction_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • You MAY need to restart the app after a flash for trackers to show 的本地化字符串。
        /// </summary>
        public static string Firmware_Device_Mode_Instruction_2 {
            get {
                return ResourceManager.GetString("Firmware_Device_Mode_Instruction_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a mode... 的本地化字符串。
        /// </summary>
        public static string Firmware_Device_Mode_Select_Placeholder {
            get {
                return ResourceManager.GetString("Firmware_Device_Mode_Select_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash Firmware 的本地化字符串。
        /// </summary>
        public static string Firmware_Flashing_Button {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done! You will need to restart your tracker 的本地化字符串。
        /// </summary>
        public static string Firmware_Flashing_Complete {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash your device&apos;s firmware 的本地化字符串。
        /// </summary>
        public static string Firmware_Flashing_Description {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upgrade/Reflash Firmware 的本地化字符串。
        /// </summary>
        public static string Firmware_Flashing_Header {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will take around ~10 seconds. Don&apos;t leave this page! 的本地化字符串。
        /// </summary>
        public static string Firmware_Flashing_Note {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAUTION!! THIS WILL FACTORY RESET YOUR TRACKER. YOU WILL NEED TO PERFORM A FIRST TIME SET UP AFTER FLASHING YOUR TRACKER. 的本地化字符串。
        /// </summary>
        public static string Firmware_Flashing_Warning {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Mode 的本地化字符串。
        /// </summary>
        public static string Firmware_ModeSetButton_Default {
            get {
                return ResourceManager.GetString("Firmware_ModeSetButton_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting mode 的本地化字符串。
        /// </summary>
        public static string Firmware_ModeSetButton_Setting {
            get {
                return ResourceManager.GetString("Firmware_ModeSetButton_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set! 的本地化字符串。
        /// </summary>
        public static string Firmware_ModeSetButton_Success {
            get {
                return ResourceManager.GetString("Firmware_ModeSetButton_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Devices 的本地化字符串。
        /// </summary>
        public static string Firmware_RefreshDevices_Default {
            get {
                return ResourceManager.GetString("Firmware_RefreshDevices_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found {0} device(s). 的本地化字符串。
        /// </summary>
        public static string Firmware_RefreshDevices_Found {
            get {
                return ResourceManager.GetString("Firmware_RefreshDevices_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refreshing 的本地化字符串。
        /// </summary>
        public static string Firmware_RefreshDevices_Refreshing {
            get {
                return ResourceManager.GetString("Firmware_RefreshDevices_Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select your tracker 的本地化字符串。
        /// </summary>
        public static string Firmware_Select_Tracker_Header {
            get {
                return ResourceManager.GetString("Firmware_Select_Tracker_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tracker connected! 的本地化字符串。
        /// </summary>
        public static string Firmware_SelectTracker_Connected {
            get {
                return ResourceManager.GetString("Firmware_SelectTracker_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Tracker 的本地化字符串。
        /// </summary>
        public static string Firmware_SelectTracker_Default {
            get {
                return ResourceManager.GetString("Firmware_SelectTracker_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The tracker did not respond. 的本地化字符串。
        /// </summary>
        public static string Firmware_SelectTracker_NoResponse {
            get {
                return ResourceManager.GetString("Firmware_SelectTracker_NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firmware 的本地化字符串。
        /// </summary>
        public static string Firmware_Title_Header {
            get {
                return ResourceManager.GetString("Firmware_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to see trackers... 的本地化字符串。
        /// </summary>
        public static string Firmware_TrackerComboBox_Default {
            get {
                return ResourceManager.GetString("Firmware_TrackerComboBox_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firmware type to flash: 的本地化字符串。
        /// </summary>
        public static string Firmware_Type_To_Flash {
            get {
                return ResourceManager.GetString("Firmware_Type_To_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect to Wifi and more 的本地化字符串。
        /// </summary>
        public static string Firmware_Wifi_Configuration_Description {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Configuration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wifi Configuration 的本地化字符串。
        /// </summary>
        public static string Firmware_Wifi_Configuration_Header {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Configuration_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set your Wi-Fi credentials 的本地化字符串。
        /// </summary>
        public static string Firmware_Wifi_Credentials_Header {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Credentials_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • If you want to use your tracker wirelessly, you NEED to set its Wifi credentials 的本地化字符串。
        /// </summary>
        public static string Firmware_Wifi_Instructions_1 {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Instructions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 • You MUST scan for Wifi networks BEFORE you can set your Wifi credentials 的本地化字符串。
        /// </summary>
        public static string Firmware_Wifi_Instructions_2 {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Instructions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WiFi Password 的本地化字符串。
        /// </summary>
        public static string Firmware_Wifi_Password_Label {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter WiFi password... 的本地化字符串。
        /// </summary>
        public static string Firmware_Wifi_Password_Placeholder {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WiFi Network Name (SSID) 的本地化字符串。
        /// </summary>
        public static string Firmware_Wifi_SSID_Label {
            get {
                return ResourceManager.GetString("Firmware_Wifi_SSID_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start typing to see WiFi networks... 的本地化字符串。
        /// </summary>
        public static string Firmware_Wifi_SSID_Placeholder {
            get {
                return ResourceManager.GetString("Firmware_Wifi_SSID_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Wifi Networks 的本地化字符串。
        /// </summary>
        public static string Firmware_WifiScanButton_Default {
            get {
                return ResourceManager.GetString("Firmware_WifiScanButton_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan failed. Click to try again. 的本地化字符串。
        /// </summary>
        public static string Firmware_WifiScanButton_Error {
            get {
                return ResourceManager.GetString("Firmware_WifiScanButton_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanning. This will take at most 30 seconds 的本地化字符串。
        /// </summary>
        public static string Firmware_WifiScanButton_Scanning {
            get {
                return ResourceManager.GetString("Firmware_WifiScanButton_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found {0} networks. Click to scan again. 的本地化字符串。
        /// </summary>
        public static string Firmware_WifiScanButton_Success {
            get {
                return ResourceManager.GetString("Firmware_WifiScanButton_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Wifi Creds 的本地化字符串。
        /// </summary>
        public static string Firmware_WifiSetButton_Default {
            get {
                return ResourceManager.GetString("Firmware_WifiSetButton_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Something went wrong... 的本地化字符串。
        /// </summary>
        public static string Firmware_WifiSetButton_Error {
            get {
                return ResourceManager.GetString("Firmware_WifiSetButton_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting WiFi credentials 的本地化字符串。
        /// </summary>
        public static string Firmware_WifiSetButton_Setting {
            get {
                return ResourceManager.GetString("Firmware_WifiSetButton_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sent! 的本地化字符串。
        /// </summary>
        public static string Firmware_WifiSetButton_Success {
            get {
                return ResourceManager.GetString("Firmware_WifiSetButton_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 en 的本地化字符串。
        /// </summary>
        public static string Godot_Locale {
            get {
                return ResourceManager.GetString("Godot_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Home_Backend_Default {
            get {
                return ResourceManager.GetString("Home_Backend_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust the brightness 的本地化字符串。
        /// </summary>
        public static string Home_Cameras_Brightness_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Brightness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Brightness 的本地化字符串。
        /// </summary>
        public static string Home_Cameras_Brightness_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Brightness_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cropping 的本地化字符串。
        /// </summary>
        public static string Home_Cameras_Cropping_Mode {
            get {
                return ResourceManager.GetString("Home_Cameras_Cropping_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip the image horizontally 的本地化字符串。
        /// </summary>
        public static string Home_Cameras_Horizontal_Flip_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Horizontal_Flip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal flip 的本地化字符串。
        /// </summary>
        public static string Home_Cameras_Horizontal_Flip_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Horizontal_Flip_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotates the image in a circle 的本地化字符串。
        /// </summary>
        public static string Home_Cameras_Rotation_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Rotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Rotation 的本地化字符串。
        /// </summary>
        public static string Home_Cameras_Rotation_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Rotation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Camera 的本地化字符串。
        /// </summary>
        public static string Home_Cameras_Start_Camera {
            get {
                return ResourceManager.GetString("Home_Cameras_Start_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Camera 的本地化字符串。
        /// </summary>
        public static string Home_Cameras_Stop_Camera {
            get {
                return ResourceManager.GetString("Home_Cameras_Stop_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tracking 的本地化字符串。
        /// </summary>
        public static string Home_Cameras_Tracking_Mode {
            get {
                return ResourceManager.GetString("Home_Cameras_Tracking_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip the image vertically 的本地化字符串。
        /// </summary>
        public static string Home_Cameras_Vertical_Flip_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Vertical_Flip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical Flip 的本地化字符串。
        /// </summary>
        public static string Home_Cameras_Vertical_Flip_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Vertical_Flip_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eye Calibration 的本地化字符串。
        /// </summary>
        public static string Home_Eye_Calibration {
            get {
                return ResourceManager.GetString("Home_Eye_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Eye Model 的本地化字符串。
        /// </summary>
        public static string Home_Eye_Load_Model {
            get {
                return ResourceManager.GetString("Home_Eye_Load_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Face Camera Address 的本地化字符串。
        /// </summary>
        public static string Home_Face_Camera_Address {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Face Camera 的本地化字符串。
        /// </summary>
        public static string Home_Face_Camera_Header {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Face Frame 的本地化字符串。
        /// </summary>
        public static string Home_Face_Camera_Select_Entire_Frame {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Select_Entire_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Face Camera Settings 的本地化字符串。
        /// </summary>
        public static string Home_Face_Camera_Settings {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Camera Address 的本地化字符串。
        /// </summary>
        public static string Home_Left_Camera_Address {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Eye Camera 的本地化字符串。
        /// </summary>
        public static string Home_Left_Camera_Header {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Left Frame 的本地化字符串。
        /// </summary>
        public static string Home_Left_Camera_Select_Entire_Frame {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Select_Entire_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Camera Settings 的本地化字符串。
        /// </summary>
        public static string Home_Left_Camera_Settings {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferred Backend 的本地化字符串。
        /// </summary>
        public static string Home_Preferred_Backend {
            get {
                return ResourceManager.GetString("Home_Preferred_Backend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Camera Address 的本地化字符串。
        /// </summary>
        public static string Home_Right_Camera_Address {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Eye Camera 的本地化字符串。
        /// </summary>
        public static string Home_Right_Camera_Header {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Right Frame 的本地化字符串。
        /// </summary>
        public static string Home_Right_Camera_Select_Entire_Frame {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Select_Entire_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Camera Settings 的本地化字符串。
        /// </summary>
        public static string Home_Right_Camera_Settings {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Home_Title_Header {
            get {
                return ResourceManager.GetString("Home_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you need help putting your tracker together, here&apos;s a useful Youtube tutorial! 的本地化字符串。
        /// </summary>
        public static string Onboarding_Assembly_Description {
            get {
                return ResourceManager.GetString("Onboarding_Assembly_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assemble Your Tracker 的本地化字符串。
        /// </summary>
        public static string Onboarding_Assembly_Header {
            get {
                return ResourceManager.GetString("Onboarding_Assembly_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re all set to start using the new Babble App! 的本地化字符串。
        /// </summary>
        public static string Onboarding_Complete_Description1 {
            get {
                return ResourceManager.GetString("Onboarding_Complete_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can revisit this page in the settings. 的本地化字符串。
        /// </summary>
        public static string Onboarding_Complete_Description2 {
            get {
                return ResourceManager.GetString("Onboarding_Complete_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setup Complete! 的本地化字符串。
        /// </summary>
        public static string Onboarding_Complete_Header {
            get {
                return ResourceManager.GetString("Onboarding_Complete_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        public static string Onboarding_Previous_Button {
            get {
                return ResourceManager.GetString("Onboarding_Previous_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip 的本地化字符串。
        /// </summary>
        public static string Onboarding_Skip_Button {
            get {
                return ResourceManager.GetString("Onboarding_Skip_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2. The Calibration can be used to tweak your eye/face expressions individually. 的本地化字符串。
        /// </summary>
        public static string Onboarding_UI_Calibration_Description {
            get {
                return ResourceManager.GetString("Onboarding_UI_Calibration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3. The Firmware Page is used to set up your device, or reset it. 的本地化字符串。
        /// </summary>
        public static string Onboarding_UI_Firmware_Description {
            get {
                return ResourceManager.GetString("Onboarding_UI_Firmware_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Where is everything? 的本地化字符串。
        /// </summary>
        public static string Onboarding_UI_Header {
            get {
                return ResourceManager.GetString("Onboarding_UI_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. The Home Page is where you can set up your cameras, and perform an eye tracking calibration. 的本地化字符串。
        /// </summary>
        public static string Onboarding_UI_Home_Description {
            get {
                return ResourceManager.GetString("Onboarding_UI_Home_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5. The Output Page shows the status of the app and other useful information. 的本地化字符串。
        /// </summary>
        public static string Onboarding_UI_Output_Description {
            get {
                return ResourceManager.GetString("Onboarding_UI_Output_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6. The Settings is for general app settings, such as theme, language and more. 的本地化字符串。
        /// </summary>
        public static string Onboarding_UI_Settings_Description {
            get {
                return ResourceManager.GetString("Onboarding_UI_Settings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4. The VRChat Page is used to alter VRChat/VRCFaceTracking specific settings. 的本地化字符串。
        /// </summary>
        public static string Onboarding_UI_VRChat_Description {
            get {
                return ResourceManager.GetString("Onboarding_UI_VRChat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This wizard will guide you through setting up the new Babble App. 的本地化字符串。
        /// </summary>
        public static string Onboarding_Welcome_Message {
            get {
                return ResourceManager.GetString("Onboarding_Welcome_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 With newer Babbles, you&apos;ll need to perform a first time setup in the Firmware tab (Icon above). 的本地化字符串。
        /// </summary>
        public static string Onboarding_Wireless_Description1 {
            get {
                return ResourceManager.GetString("Onboarding_Wireless_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It only takes 2 minutes! Select your tracker and mode (wired or wireless). It&apos;s that simple. 的本地化字符串。
        /// </summary>
        public static string Onboarding_Wireless_Description2 {
            get {
                return ResourceManager.GetString("Onboarding_Wireless_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wired or Wireless? 的本地化字符串。
        /// </summary>
        public static string Onboarding_Wireless_Header {
            get {
                return ResourceManager.GetString("Onboarding_Wireless_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please note newer trackers have a 20-second window before they enter camera mode. 的本地化字符串。
        /// </summary>
        public static string Onboarding_Wireless_Note {
            get {
                return ResourceManager.GetString("Onboarding_Wireless_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy the log&apos;s output to your clipboard 的本地化字符串。
        /// </summary>
        public static string Output_CopyButton_Tooltip {
            get {
                return ResourceManager.GetString("Output_CopyButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the logging directory 的本地化字符串。
        /// </summary>
        public static string Output_OpenLoggingDirectoryButton_Tooltip {
            get {
                return ResourceManager.GetString("Output_OpenLoggingDirectoryButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save the log&apos;s output 的本地化字符串。
        /// </summary>
        public static string Output_SaveButton_Tooltip {
            get {
                return ResourceManager.GetString("Output_SaveButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 的本地化字符串。
        /// </summary>
        public static string Output_Title_Header {
            get {
                return ResourceManager.GetString("Output_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Advanced_Description {
            get {
                return ResourceManager.GetString("Settings_Advanced_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable advanced settings 的本地化字符串。
        /// </summary>
        public static string Settings_Advanced_Header {
            get {
                return ResourceManager.GetString("Settings_Advanced_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runs the ETVT&apos;s model for Eyelid Tracking / smoother blinks (higher CPU/GPU usage) 的本地化字符串。
        /// </summary>
        public static string Settings_EyelidEnhancer_Description {
            get {
                return ResourceManager.GetString("Settings_EyelidEnhancer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use eyelid enhancer 的本地化字符串。
        /// </summary>
        public static string Settings_EyelidEnhancer_Header {
            get {
                return ResourceManager.GetString("Settings_EyelidEnhancer_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both Eyes 的本地化字符串。
        /// </summary>
        public static string Settings_EyelidMode_Both {
            get {
                return ResourceManager.GetString("Settings_EyelidMode_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choosing a single-eye mode (LeftOnly or RightOnly) can reduce GPU/CPU usage 的本地化字符串。
        /// </summary>
        public static string Settings_EyelidMode_Description {
            get {
                return ResourceManager.GetString("Settings_EyelidMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eyes for eyelid  的本地化字符串。
        /// </summary>
        public static string Settings_EyelidMode_Header {
            get {
                return ResourceManager.GetString("Settings_EyelidMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Eye 的本地化字符串。
        /// </summary>
        public static string Settings_EyelidMode_LeftOnly {
            get {
                return ResourceManager.GetString("Settings_EyelidMode_LeftOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Eye 的本地化字符串。
        /// </summary>
        public static string Settings_EyelidMode_RightOnly {
            get {
                return ResourceManager.GetString("Settings_EyelidMode_RightOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_Description {
            get {
                return ResourceManager.GetString("Settings_Filter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn filtering on or off. 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_Enabled_Description {
            get {
                return ResourceManager.GetString("Settings_Filter_Enabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_Enabled_Label {
            get {
                return ResourceManager.GetString("Settings_Filter_Enabled_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One-Euro filter settings 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_Header {
            get {
                return ResourceManager.GetString("Settings_Filter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls how much smoothing is applied to slow movements 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_MinFreq_Description {
            get {
                return ResourceManager.GetString("Settings_Filter_MinFreq_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum frequency cutoff 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_MinFreq_Label {
            get {
                return ResourceManager.GetString("Settings_Filter_MinFreq_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines how the filter adapts when you move faster 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_Speed_Description {
            get {
                return ResourceManager.GetString("Settings_Filter_Speed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed coefficient 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_Speed_Label {
            get {
                return ResourceManager.GetString("Settings_Filter_Speed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High ({0}) 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_Template_High {
            get {
                return ResourceManager.GetString("Settings_Filter_Template_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low ({0}) 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_Template_Low {
            get {
                return ResourceManager.GetString("Settings_Filter_Template_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium ({0}) 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_Template_Medium {
            get {
                return ResourceManager.GetString("Settings_Filter_Template_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select from a template 的本地化字符串。
        /// </summary>
        public static string Settings_Filter_Template_Placeholder {
            get {
                return ResourceManager.GetString("Settings_Filter_Template_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch 的本地化字符串。
        /// </summary>
        public static string Settings_FirstTime_Button {
            get {
                return ResourceManager.GetString("Settings_FirstTime_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relaunches the first time setup 的本地化字符串。
        /// </summary>
        public static string Settings_FirstTime_Description {
            get {
                return ResourceManager.GetString("Settings_FirstTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch first time setup 的本地化字符串。
        /// </summary>
        public static string Settings_FirstTime_Header {
            get {
                return ResourceManager.GetString("Settings_FirstTime_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use your GPU to make things run faster! Requires restart 的本地化字符串。
        /// </summary>
        public static string Settings_GPU_Description {
            get {
                return ResourceManager.GetString("Settings_GPU_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use GPU acceleration 的本地化字符串。
        /// </summary>
        public static string Settings_GPU_Header {
            get {
                return ResourceManager.GetString("Settings_GPU_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Afrikaans 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Afrikaans {
            get {
                return ResourceManager.GetString("Settings_Language_Afrikaans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arabic 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Arabic {
            get {
                return ResourceManager.GetString("Settings_Language_Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Catalan 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Catalan {
            get {
                return ResourceManager.GetString("Settings_Language_Catalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Chinese {
            get {
                return ResourceManager.GetString("Settings_Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese (Simplified) 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Chinese_Simplified {
            get {
                return ResourceManager.GetString("Settings_Language_Chinese_Simplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese (Traditional) 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Chinese_Traditional {
            get {
                return ResourceManager.GetString("Settings_Language_Chinese_Traditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Czech 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Czech {
            get {
                return ResourceManager.GetString("Settings_Language_Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Danish 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Danish {
            get {
                return ResourceManager.GetString("Settings_Language_Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Default {
            get {
                return ResourceManager.GetString("Settings_Language_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the app&apos;s language. Switch pages to apply. 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Description {
            get {
                return ResourceManager.GetString("Settings_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dutch 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Dutch {
            get {
                return ResourceManager.GetString("Settings_Language_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finnish 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Finnish {
            get {
                return ResourceManager.GetString("Settings_Language_Finnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 French 的本地化字符串。
        /// </summary>
        public static string Settings_Language_French {
            get {
                return ResourceManager.GetString("Settings_Language_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 German 的本地化字符串。
        /// </summary>
        public static string Settings_Language_German {
            get {
                return ResourceManager.GetString("Settings_Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greek 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Greek {
            get {
                return ResourceManager.GetString("Settings_Language_Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Header {
            get {
                return ResourceManager.GetString("Settings_Language_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hebrew 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Hebrew {
            get {
                return ResourceManager.GetString("Settings_Language_Hebrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hungarian 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Hungarian {
            get {
                return ResourceManager.GetString("Settings_Language_Hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italian 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Italian {
            get {
                return ResourceManager.GetString("Settings_Language_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日本語 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Japanese {
            get {
                return ResourceManager.GetString("Settings_Language_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 한국어 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Korean {
            get {
                return ResourceManager.GetString("Settings_Language_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Norwegian 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Norwegian {
            get {
                return ResourceManager.GetString("Settings_Language_Norwegian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polski 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Polish {
            get {
                return ResourceManager.GetString("Settings_Language_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portuguese (Brazil) 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Portuguese_Brazil {
            get {
                return ResourceManager.GetString("Settings_Language_Portuguese_Brazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portuguese (Portugal) 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Portuguese_Portugal {
            get {
                return ResourceManager.GetString("Settings_Language_Portuguese_Portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Romanian 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Romanian {
            get {
                return ResourceManager.GetString("Settings_Language_Romanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Russian 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Russian {
            get {
                return ResourceManager.GetString("Settings_Language_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serbian 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Serbian {
            get {
                return ResourceManager.GetString("Settings_Language_Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Español 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Spanish {
            get {
                return ResourceManager.GetString("Settings_Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swedish 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Swedish {
            get {
                return ResourceManager.GetString("Settings_Language_Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turkish 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Turkish {
            get {
                return ResourceManager.GetString("Settings_Language_Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ukrainian 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Ukrainian {
            get {
                return ResourceManager.GetString("Settings_Language_Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vietnamese 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Vietnamese {
            get {
                return ResourceManager.GetString("Settings_Language_Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum logging level. Requires restart 的本地化字符串。
        /// </summary>
        public static string Settings_LogLevel_Description {
            get {
                return ResourceManager.GetString("Settings_LogLevel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Level Verbosity 的本地化字符串。
        /// </summary>
        public static string Settings_LogLevel_Header {
            get {
                return ResourceManager.GetString("Settings_LogLevel_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Where should OSC data be sent? 的本地化字符串。
        /// </summary>
        public static string Settings_OSC_Description {
            get {
                return ResourceManager.GetString("Settings_OSC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OSC 的本地化字符串。
        /// </summary>
        public static string Settings_OSC_Header {
            get {
                return ResourceManager.GetString("Settings_OSC_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP Address 的本地化字符串。
        /// </summary>
        public static string Settings_OSC_IP_Label {
            get {
                return ResourceManager.GetString("Settings_OSC_IP_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OSC Prefix 的本地化字符串。
        /// </summary>
        public static string Settings_OSC_Prefix_Label {
            get {
                return ResourceManager.GetString("Settings_OSC_Prefix_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recalibrate Address 的本地化字符串。
        /// </summary>
        public static string Settings_OSC_Recalibrate_Label {
            get {
                return ResourceManager.GetString("Settings_OSC_Recalibrate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receive Port 的本地化字符串。
        /// </summary>
        public static string Settings_OSC_ReceivePort_Label {
            get {
                return ResourceManager.GetString("Settings_OSC_ReceivePort_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recenter Address 的本地化字符串。
        /// </summary>
        public static string Settings_OSC_Recenter_Label {
            get {
                return ResourceManager.GetString("Settings_OSC_Recenter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Port 的本地化字符串。
        /// </summary>
        public static string Settings_OSC_SendPort_Label {
            get {
                return ResourceManager.GetString("Settings_OSC_SendPort_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you are using Baballonia with VRCFaceTracking, there is no need to change these ports 的本地化字符串。
        /// </summary>
        public static string Settings_OSC_VRCFT_Warning {
            get {
                return ResourceManager.GetString("Settings_OSC_VRCFT_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Should the app launch with SteamVR? (Change requires a SteamVR restart.) 的本地化字符串。
        /// </summary>
        public static string Settings_SteamVR_Auto_Start_Description {
            get {
                return ResourceManager.GetString("Settings_SteamVR_Auto_Start_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Start with SteamVR 的本地化字符串。
        /// </summary>
        public static string Settings_SteamVR_Auto_Start_Header {
            get {
                return ResourceManager.GetString("Settings_SteamVR_Auto_Start_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_Dark_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_Default_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Default_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select which app theme to display 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App theme 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_Header {
            get {
                return ResourceManager.GetString("Settings_Theme_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_Light_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Light_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Title_Header {
            get {
                return ResourceManager.GetString("Settings_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Should the app check for updates on start? 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_Description {
            get {
                return ResourceManager.GetString("Settings_Updates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check For Updates 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_Header {
            get {
                return ResourceManager.GetString("Settings_Updates_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send only eye, only face or both? (Change requires VRCFT restart) 的本地化字符串。
        /// </summary>
        public static string VRC_ModuleMode_Description {
            get {
                return ResourceManager.GetString("VRC_ModuleMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set VRCFT module mode 的本地化字符串。
        /// </summary>
        public static string VRC_ModuleMode_Header {
            get {
                return ResourceManager.GetString("VRC_ModuleMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a mode... 的本地化字符串。
        /// </summary>
        public static string VRC_ModuleMode_Placeholder {
            get {
                return ResourceManager.GetString("VRC_ModuleMode_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VRChat + VRCFaceTracking Settings 的本地化字符串。
        /// </summary>
        public static string VRC_Title_Header {
            get {
                return ResourceManager.GetString("VRC_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brings eye tracking to avatars that do not have VRCFaceTracking 的本地化字符串。
        /// </summary>
        public static string VRC_UseNativeEyeTracking_Description {
            get {
                return ResourceManager.GetString("VRC_UseNativeEyeTracking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Native VRC Eye Tracking 的本地化字符串。
        /// </summary>
        public static string VRC_UseNativeEyeTracking_Header {
            get {
                return ResourceManager.GetString("VRC_UseNativeEyeTracking_Header", resourceCulture);
            }
        }
    }
}
